### ISSUE TITLE
Super Resolution Implementation

### ISSUE THREAD

**Issue by tprdk** [JunlinHan/DCLGAN#5]
Hi, thanks for your great work.
I just check out your paper and it seem quite well on domain translation tasks and wanna try this work on super resolution task.
I tried to set one generator model up sampling size to 0 and another one's up sampling size 2. But it gives me incorrect channel size error. Can you give me any advice about how can i implement this?

**Comment by JunlinHan** [comment]
Hi tprdk, thanks for your issues.
The super-res network is often different from the image-to-image translation network. I recommend that you use the super-res network as the generator.

If you want to modify this one, you might need to carefully check the shape of output tensors in each CNN layer. I guess the case you encounter is due to  input_nc (int) and output_nc (int) do not align between 2 generators. Also, changing the up sampling size may affect h/w dimension. You might need to check this.

**Comment by tprdk** [comment]
Thanks for your quick reply. 
I will try to implement this as you suggest. Really appreciate for your detailed answer.
